name: ZMK Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: promicro_nrf52840
            shield: cygnus_left
          - board: promicro_nrf52840
            shield: cygnus_right

    steps:
      - uses: actions/checkout@v4

      - uses: zmkfirmware/zmk/.github/actions/build@main
        with:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}
          config: config
