name: ZMK Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: zmkfirmware/zmk/.github/actions/build-user-config@main
        with:
          config_path: config
          board: promicro_nrf52840
          shield: cygnus_left,cygnus_right
